# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desktop/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(576, 370)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pb_send = QtWidgets.QPushButton(self.centralwidget)
        self.pb_send.setGeometry(QtCore.QRect(100, 250, 81, 31))
        self.pb_send.setObjectName("pb_send")
        self.list_pos = QtWidgets.QListWidget(self.centralwidget)
        self.list_pos.setGeometry(QtCore.QRect(10, 10, 171, 192))
        self.list_pos.setObjectName("list_pos")
        self.input_x = QtWidgets.QTextEdit(self.centralwidget)
        self.input_x.setGeometry(QtCore.QRect(10, 210, 81, 31))
        self.input_x.setObjectName("input_x")
        self.pb_save = QtWidgets.QPushButton(self.centralwidget)
        self.pb_save.setGeometry(QtCore.QRect(10, 250, 81, 31))
        self.pb_save.setObjectName("pb_save")
        self.input_y = QtWidgets.QTextEdit(self.centralwidget)
        self.input_y.setGeometry(QtCore.QRect(100, 210, 81, 31))
        self.input_y.setObjectName("input_y")
        self.pb_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pb_clear.setGeometry(QtCore.QRect(10, 290, 81, 31))
        self.pb_clear.setObjectName("pb_clear")
        self.pb_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pb_stop.setGeometry(QtCore.QRect(100, 290, 81, 31))
        self.pb_stop.setObjectName("pb_stop")
        self.pb_move_forward = QtWidgets.QPushButton(self.centralwidget)
        self.pb_move_forward.setGeometry(QtCore.QRect(330, 70, 81, 31))
        self.pb_move_forward.setObjectName("pb_move_forward")
        self.pb_turn_right = QtWidgets.QPushButton(self.centralwidget)
        self.pb_turn_right.setGeometry(QtCore.QRect(420, 130, 101, 31))
        self.pb_turn_right.setObjectName("pb_turn_right")
        self.pb_move_backward = QtWidgets.QPushButton(self.centralwidget)
        self.pb_move_backward.setGeometry(QtCore.QRect(330, 190, 81, 31))
        self.pb_move_backward.setObjectName("pb_move_backward")
        self.pb_turn_left = QtWidgets.QPushButton(self.centralwidget)
        self.pb_turn_left.setGeometry(QtCore.QRect(220, 130, 101, 31))
        self.pb_turn_left.setObjectName("pb_turn_left")
        self.pb_move_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pb_move_stop.setGeometry(QtCore.QRect(330, 130, 81, 31))
        self.pb_move_stop.setObjectName("pb_move_stop")
        self.pb_reset_pos = QtWidgets.QPushButton(self.centralwidget)
        self.pb_reset_pos.setGeometry(QtCore.QRect(460, 280, 81, 31))
        self.pb_reset_pos.setObjectName("pb_reset_pos")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 576, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pb_send.setText(_translate("MainWindow", "Kirim"))
        self.pb_save.setText(_translate("MainWindow", "Simpan"))
        self.pb_clear.setText(_translate("MainWindow", "Hapus"))
        self.pb_stop.setText(_translate("MainWindow", "Stop"))
        self.pb_move_forward.setText(_translate("MainWindow", "Maju"))
        self.pb_turn_right.setText(_translate("MainWindow", "Belok Kanan"))
        self.pb_move_backward.setText(_translate("MainWindow", "Mundur"))
        self.pb_turn_left.setText(_translate("MainWindow", "Belok Kiri"))
        self.pb_move_stop.setText(_translate("MainWindow", "Stop"))
        self.pb_reset_pos.setText(_translate("MainWindow", "Reset"))
